name: Generate Article
on:
    push:
        branches:
            - main
jobs:
    check-file-name-validity:
        name: Check file name validity
        runs-on: ubuntu-latest
        steps:
            - name: Clone GitHub Repo
                uses: actions/checkout@v4

            - name: Find blank article file
              run: |
                cd blog |
                FILE=$(find "$file" -size 0)
                echo "Blank article file: $FILE"