name: Generate Article

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  generate-article:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GitHub Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Find blank article file
        run: |
          cd blog
          FILE="$(find . -type f -empty -print -quit)"
          FILE="${FILE#./}"
          echo "FILE=$FILE" >> $GITHUB_ENV
          echo "Blank article file: $FILE"

      - name: Check if file name is valid
        run: |
          if ! echo "$FILE" | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}-[a-z0-9]+(-[a-z0-9]+)*\.md$'; then
            echo "Nom de fichier invalide : $FILE"
            echo "Format attendu : YYYY-MM-DD-nom-de-l-article.md"
            exit 1
          else
            echo "Nom de fichier valide : $FILE"
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 26
      
      - name: Install OpenAI
        run: npm install openai
      
      - name: OpenAI link and generate article
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node ./scripts/write-article.js

      - name: Save article as artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-article
          path: blog/${{ env.FILE }}

      - name: Commit and push changes
        run: |
          git config --global user.name "OtterBot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add blog/${{ env.FILE }}
          git commit -m "Generate article: ${{ env.FILE }}"
          git push

      - name: Get Article Title & Summary
        id: get_title_summary
        run: |
          TITLE=$(grep '^title:' "blog/${{ env.FILE }}" | sed 's/title: "\(.*\)"/\1/')
          SUMMARY=$(grep '^summary:' "blog/${{ env.FILE }}" | sed 's/summary: "\(.*\)"/\1/')
          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "SUMMARY=$SUMMARY" >> $GITHUB_ENV

      - name: Add comment to Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Article généré automatiquement

                **Titre :** ${{ env.TITLE }}

                **Résumé :** ${{ env.SUMMARY }}

                L’article a été généré automatiquement. Merci de le relire avant de merger cette Pull Request.`
            });