name: Implement Article

on:
    push:
        branches:
            - main
        paths:
            - 'blog/**'

jobs:
    implement-article:
        runs-on: ubuntu-latest
        steps:
            - name: Clone GitHub Repo
              uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}

            - name: Find new article file
              run: |
                cd blog
                FILE="$(find . -type f -newermt '1 minute ago' -print -quit)"
                FILE="${FILE#./}"
                echo "FILE=$FILE" >> $GITHUB_ENV


            - name: Get Article Title & Summary
              id: get_title_summary
              run: |
                TITLE=$(grep '^title:' "blog/${{ env.FILE }}" | sed 's/title: "\(.*\)"/\1/')
                SUMMARY=$(grep '^summary:' "blog/${{ env.FILE }}" | sed 's/summary: "\(.*\)"/\1/')
                echo "TITLE=$TITLE" >> $GITHUB_ENV
                echo "SUMMARY=$SUMMARY" >> $GITHUB_ENV

            - name: Send Discord Message
              env:
                DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
              uses: Ilshidur/action-discord@0.4.0
              with:
                args: |
                    Nouvel article généré : **${{ env.TITLE }}**
                    
                    Résumé : ${{ env.SUMMARY }}
                    
                    L’article a été généré automatiquement. Merci de le relire avant de merger cette Pull Request.

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 26

            - name: Install dependencies
              run: npm i @wcj/markdown-to-html

            - name: Get article content
              id: get_article_content
              run: |
                CONTENT=$(cat "blog/${{ env.FILE }}")
                echo "CONTENT<<EOF" >> $GITHUB_ENV
                echo "$CONTENT" >> $GITHUB_ENV
                echo "EOF" >> $GITHUB_ENV
            
            - name: Create HTML file
              run: |
                FILE_NAME=$(basename "${{ env.FILE }}" .md)
                echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
                echo "Creating HTML file: public/blog/${{ env.FILE_NAME }}.html"
                touch "./public/blog/${{ env.FILE_NAME }}.html"
                                  
            - name: Convert article to HTML
              run: node ./scripts/convert-to-html.js